services:
  node-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - fullstackapp
    env_file:
      - ./backend/.env
    environment:
      - CLIENT_URL=http://localhost:3000
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:4000/api  # For browser access
    networks:
      - fullstackapp
    ports:
      - "3000:3000"
    depends_on:
      - node-app  # Assuming your backend service is named 'backend'
      
  mongo: 
    image: deaddeal96/ticket-hub-db:latest
    restart: always
    networks:
      - fullstackapp
    volumes:
      - myfullstackvol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - fullstackapp
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo

networks:
  fullstackapp:
    driver: bridge
volumes:
  myfullstackvol:
  