apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: ticket-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-backend
  template:
    metadata:
      labels:
        app: ticket-backend
    spec:
      containers:
      - name: ticket-backend
        image: deaddeal96/ticket-hub-back:latest
        imagePullPolicy: IfNotPresent   
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_URI
          value: mongodb://admin:12345@mongo-service:27017/?authSource=admin
        - name: JWT_SECRET 
          valueFrom: 
            secretKeyRef:
              name: backend-secrets
              key: JWT_SECRET
        - name: CLIENT_URL
          value: http://ticket-hub.local 

---
apiVersion: v1
kind: Service
metadata:
  name: ticket-backend-service
spec:
  selector:
    app: ticket-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000