apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticket-hub-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: ticket-hub.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ticket-backend-service
            port:
              number: 4000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ticket-frontend-service
            port:
              number: 3000