name: ci cd of Ticket-hub-frontend
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose environment"
        required: true
        default: "staging"
jobs:
    ticket-hub-frontend:
      runs-on: ubuntu-latest
      

      steps:
        - name: checkout code 
          uses: actions/checkout@v5.0.0
        - name: Docker Setup Buildx 
          uses: docker/setup-buildx-action@v3.11.1

        - name: Docker Login
          uses: docker/login-action@v3.5.0
          with:
            username: ${{secrets.DOCKER_USERNAME}} 
            password: ${{secrets.DOCKER_PASS}}  
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.18.0
          with: 
            context: .
            file: ./frontend/Dockerfile
            push: true
            tags:  deaddeal96/ticket-hub-front:latest
