name: ci cd of Ticket-hub-frontend
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose environment"
        required: true
        default: "staging"
jobs:
    ticket-hub-frontend:
      runs-on: ubuntu-latest
      

      steps:
        - name: checkout code 
          uses: actions/checkout@v5.0.0
        - name: Docker Setup Buildx 
          uses: docker/setup-buildx-action@v3.11.1

        - name: sonarqube
          run: |
              npm ci
              npm run build --if-present
              npx sonar-scanner \
              -Dsonar.projectKey=mofayad96_ticket-hub-frontend \
              -Dsonar.organization=mofayad96 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        
        - name: Docker Login
          uses: docker/login-action@v3.5.0
          with:
            username: ${{secrets.DOCKER_USERNAME}} 
            password: ${{secrets.DOCKER_PASS}}  
        
        - name: Build frontend image
          uses: docker/build-push-action@v6
          with:
            context: ./frontend       
            file: ./frontend/Dockerfile
            push: true
            tags: deaddeal96/ticket-hub-front:latest
