name: ci cd of Ticket-hub-backend
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose environment"
        required: true
        default: "staging"
jobs:
    spring-petclinic-CI-CD:
      runs-on: ubuntu-latest
      

      steps:
        - name: checkout code 
          uses: actions/checkout@v5.0.0
        - name: Setup Node.js environment
          uses: actions/setup-node@v6.0.0 
          with:
            node-version: '22'       
            cache: 'npm' 
        - name : build app using npm
          run: npm ci
        