name: ci cd of Ticket-hub-backend
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: "choose environment"
        required: true
        default: "staging"
jobs:
    ticket-hub-backend:
      runs-on: ubuntu-latest
      

      steps:
        - name: checkout code 
          uses: actions/checkout@v5.0.0

        - name: Docker Setup Buildx 
          uses: docker/setup-buildx-action@v3.11.1
        
        - name: sonarqube
          working-directory: ./backend
          run: |
              npm ci
              npm run build --if-present
              npx sonar-scanner \
              -Dsonar.projectKey=mofayad96_ticket-hub-back \
              -Dsonar.organization=mofayad96 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${{ secrets.SONAR_TOKEN }}

        

        - name: Docker Login
          uses: docker/login-action@v3.5.0
          with:
            username: ${{secrets.DOCKER_USERNAME}} 
            password: ${{secrets.DOCKER_PASS}}
        
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.18.0
          with: 
            context: ./backend
            file: ./backend/Dockerfile
            push: true
            tags:  deaddeal96/ticket-hub-back:latest

        - name: Trivy vulnerability scan
          uses: aquasecurity/trivy-action@master
          with:
            image-ref: 'deaddeal96/ticket-hub-back:latest'
            format: 'json'
            severity: 'CRITICAL,HIGH'
            output: '${{ github.workspace }}/trivy-report2.json' 

        - name: Upload Trivy JSON report
          uses: actions/upload-artifact@v4
          with:
              name: trivy-report
              path: '${{ github.workspace }}/trivy-report2.json'
